//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FabricStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialDelivery
    {
        public int ID { get; set; }
        public int Delivery { get; set; }
        public int Material { get; set; }
        public double CountMeters { get; set; }
        public double PriceForDelievery { get; set; }
        public System.DateTime DateDelievery { get; set; }
    
        public virtual Delivery Delivery1 { get; set; }
        public virtual Material Material1 { get; set; }
    }
}
