//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FabricStore
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    public partial class SaleMaterial
    {
        public int ID { get; set; }
        public int Material { get; set; }
        public double Count { get; set; }
        public System.DateTime DateSale { get; set; }
        public int Payment { get; set; }
        
        public double Price
        {
            get
            {
                bdMaterialsEntities context = new bdMaterialsEntities();
                double priceForMeter = (from x in context.Materials
                                     where Material == x.ID
                                     select x.Price).Sum();
                return priceForMeter*this.Count;
            }
            set { }
        }
        public virtual Material Material1 { get; set; }
        public virtual Payment Payment1 { get; set; }
    }
}
